---
title: "Crack-analysis"
author: "Daniel Alejandro Cruz Pérez"
date: "1/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(plyr)
library(igraph)

library(knitr)
library(factoextra)
library(scales)
library(ggplot2)
library(cluster)
library(fpc)

#"di1a", Marihuana
#"di1b", Cocaína
#"di1c", Crack
#"di1d", Alucinógenos
#"di1e", Inhalantes
#"di1f", Heroína
#"di1g", Estimulantes
#"di1h", Ketamina
#"dm1d", Tranquilizante
#"dm1b", Anfetamina
#tb02 tabaco
#al alcohol

data <- read.csv("../data/crack-anylisis.csv", stringsAsFactors = FALSE)
data$X <- NULL


data1 <- data[data$di1c==1,]
data1[data1$desc_ent=="30 VERACRUZ DE IGNACIO DE LA LLAVE",]$desc_ent <- '30 VERACRUZ'
data1[data1$desc_ent=="16 MICHOAC_N DE OCAMPO",]$desc_ent <- '16 MICHOAC_N '

state <- data1$desc_ent


remp.val <- function(variable){
  variable <- ifelse(is.na(variable), -1, variable)
  variable <- ifelse(variable>98, -1, variable)
  return(variable)
}

data1 <- as.data.frame(apply(data1[,-c(2)], 2, remp.val))
data1$desc_ent <- state

#Por sexo
#sort(unique(data1$ds2))
#summary(data1)
sex <- as.factor(mapvalues(data1$ds2, from=c(1,2), to=c("Hombres", "Mujeres")))

#Toma de las edades
#sort(unique(data1$ds3))
#summary(data1)
ages <- cut(data1$ds3, breaks=c(10,20,30,40,50,60,70), 
            labels=c("10-20",
                     "21-30",
                     "31-40",
                     "41-50",
                     "51-60",
                     "61-70"))

#Se considera indigena?
#sort(unique(data1$ds5a))
#summary(data1)
indi <- as.factor(mapvalues(data1$ds5a, from=c(1,2), to=c("Si", "No")))

#Estado civíl
#sort(unique(data1$ds6))
#summary(data1)
status <- as.factor(mapvalues(data1$ds6, from=c(1,2,3,4,5,6), to=c("Casado(a)",
                                                                  "Unión libre",
                                                                  "Separado(a)",
                                                                  "Divorsiado(a)",
                                                                  "Viudo(a)",
                                                                  "Soltero(a)")))

#Religion
#sort(unique(data1$ds7))
#summary(data1)
religion <- as.factor(mapvalues(data1$ds7, from=c(1,2,3,4,5,6), to=c("Católica", 
                                                                    "Protestante/Evangélica",
                                                                    "Judáica",
                                                                    "Cristiana",
                                                                    "Otra",
                                                                    "Ninguna religión")))

#Estudia actualmente?
#sort(unique(data1$ds8))
#summary(data1)
actual_study <- as.factor(mapvalues(data1$ds8, from=c(1,2,3), to=c("No, nunca ha estudiado",
                                                                   "No, pero si ha estudiado",
                                                                   "Si")))

#Ultimo grado de estudios
#sort(unique(data1$ds9))
#summary(data1)
last_study <- as.factor(mapvalues(data1$ds9, from=c(1,2,3,4,5,6,7,8,-1), 
                                  to=c("Primaria incompleta",
                                       "Primaria completa",
                                       "Secundaria incompleta",
                                       "Secundaria completa",
                                       "Bachillerato incompleto",
                                       "Bachillerato completo",
                                       "Licenciatura incompleta",
                                       "Licenciatura completa",
                                       "No contesta")))

#Ha trabajado en los ultimos 30 días
#sort(unique(data1$ds10))
#summary(data1)
did_work <- as.factor(mapvalues(data1$ds10, from=c(1,2), to=c("Si", "No")))

#Por qué motivo no trabaja
#sort(unique(data1$ds14))
#summary(data1)
why_work <- as.factor(mapvalues(data1$ds14, from=c(1,2,3,4,5,7,9,10,12,13,-1), 
                                to=c("Se dedica al hogar", 
                                     "Estudia",
                                     "Es jubilado",
                                     "Incapacidad permanente",
                                     "Es rentista",
                                     "Desempleado",
                                     "Jornada especial",
                                     "Incapacidad temporal",
                                     "Desastre natural",
                                     "Otras razones",
                                     "Si trabaja")))

#Cual es su ocupación
#sort(unique(data1$ds16))
#summary(data1)
work <- as.factor(mapvalues(data1$ds16, from=c(1,2,4,5,6,7,8,9,10,11,12,13,14,15), 
                            to=c("Profesionista", 
                                 "Maestro",
                                 "Microempresario",
                                 "Oficinista",
                                 "Obrero calificado",
                                 "Obrero no calificado",
                                 "Agricultor",
                                 "Campesino",
                                 "Subempleado",
                                 "Estudiante",
                                 "Ama/o de casa",
                                 "Jubilado",
                                 "Incapacidad permanente",
                                 "Otro")))

#Ha tenido hijos
#sort(unique(data1$ds21))
#summary(data1)
sons <- as.factor(mapvalues(data1$ds21, from=c(1,2), to=c("Si", "No")))

#Cuantos
#sort(unique(data1$ds22))
#summary(data1)
much_sons <- as.factor(mapvalues(data1$ds22, from=c(0,1,2,3,4,5,6,-1), 
                                 to=c("No tiene", 
                                      "1",
                                      "2",
                                      "3",
                                      "4",
                                      "5",
                                      "6", 
                                      "Prefiere no decir")))

#Hijos en drogas
#sort(unique(data1$ds23))
#summary(data1)
sons_drugs <- as.factor(mapvalues(data1$ds23, from=c(1,2,-1), 
                                  to=c("Si", 
                                       "No",
                                       "No contesta")))

#A que edad comienza a usar crack
#sort(unique(data1$di4c))
#summary(data1)
ages_cra <- cut(data1$di4c, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                labels=c("No ha usado",
                         "1-10",
                         "11-20",
                         "21-30",
                         "31-40",
                         "41-50",
                         "51-60",
                         "Más de 61"))

#Tabaco
#sort(unique(data1$tb02))
#summary(data1)
tabaco_any <- as.factor(mapvalues(data1$tb02, from=c(1,2,3,7,9),
                                  to=c("Todos los días",
                                       "Algunos días",
                                       "No fuma actualmente",
                                       "No sabe",
                                       "No responde")))

#edad en que comienza
#sort(unique(data1$tb06))
#summary(data1)
ages_tabaco <- cut(data1$tb06, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                   labels=c("No fuma",
                            "1-10",
                            "11-20",
                            "21-30",
                            "31-40",
                            "41-50",
                            "51-60",
                            "Más de 61"))

#Tranquilizantes
#sort(unique(data1$dm1b))
#summary(data1)
tranq_any <- as.factor(mapvalues(data1$dm1b, from=c(1,2,9),
                                 to=c("Si",
                                      "No",
                                      "No responde/No sabe")))

#Edad tranquilizantes
#sort(unique(data1$dm4b))
#summary(data1)
ages_tranq <- cut(data1$dm4b, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                  labels=c("No ha usado",
                           "1-10",
                           "11-20",
                           "21-30",
                           "31-40",
                           "41-50",
                           "51-60",
                           "Más de 61"))

#Anfetamínicos
#sort(unique(data1$dm1d))
#summary(data1)
anf_any <- as.factor(mapvalues(data1$dm1d, from=c(1,2,9),
                               to=c("Si",
                                    "No",
                                    "No responde/No sabe")))
#edad anfetamínicos
#sort(unique(data1$dm4d))
#summary(data1)
ages_anf <- cut(data1$dm4d, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                labels=c("No ha usado",
                         "1-10",
                         "11-20",
                         "21-30",
                         "31-40",
                         "41-50",
                         "51-60",
                         "Más de 61"))

#Marihuana
#sort(unique(data1$di1a))
#summary(data1)
mar_any <- as.factor(mapvalues(data1$di1a, from=c(1,2,9),
                               to=c("Si",
                                    "No",
                                    "No responde/No sabe")))

#Edad marihuana
#sort(unique(data1$di4a))
ages_mar <- cut(data1$di4a, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                labels=c("No ha usado",
                         "1-10",
                         "11-20",
                         "21-30",
                         "31-40",
                         "41-50",
                         "51-60",
                         "Más de 61"))

#cocaína
#sort(unique(data1$di1b))
#summary(data1)
coc_any <- as.factor(mapvalues(data1$di1b, from=c(1,2),
                               to=c("Si",
                                    "No")))

#años cocaína
#sort(unique(data1$di4b))
#summary(data1)
ages_coc <- cut(data1$di4b, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                labels=c("No ha usado",
                         "1-10",
                         "11-20",
                         "21-30",
                         "31-40",
                         "41-50",
                         "51-60",
                         "Más de 61"))

#Crack
#sort(unique(data1$di1c))
#summary(data1)
#cra_any <- as.factor(mapvalues(data$di1c, from=c(1,2,9),
#                               to=c("Si",
#                                    "No",
#                                    "No responde/No sabe")))

#Crack años
#sort(unique(data1$di4c))
#summary(data1)
ages_cra <- cut(data1$di4c, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                labels=c("No ha usado",
                         "1-10",
                         "11-20",
                         "21-30",
                         "31-40",
                         "41-50",
                         "51-60",
                         "Más de 61"))

#Alucinógenos
#sort(unique(data1$di1d))
#summary(data1)
alu_any <- as.factor(mapvalues(data1$di1d, from=c(1,2,9),
                               to=c("Si",
                                    "No",
                                    "No responde/No sabe")))

#Alucinógenos años
#sort(unique(data1$di4d))
#summary(data1)
ages_alu <- cut(data1$di4d, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                labels=c("No ha usado",
                         "1-10",
                         "11-20",
                         "21-30",
                         "31-40",
                         "41-50",
                         "51-60",
                         "Más de 61"))

#Inhalantes
#sort(unique(data1$di1e))
#summary(data1)
ina_any <- as.factor(mapvalues(data1$di1e, from=c(1,2,9),
                               to=c("Si",
                                    "No",
                                    "No responde/No sabe")))

#Inhalanes años
#sort(unique(data1$di4e))
ages_ina <- cut(data1$di4e, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                labels=c("No ha usado",
                         "1-10",
                         "11-20",
                         "21-30",
                         "31-40",
                         "41-50",
                         "51-60",
                         "Más de 61"))

#Heroína
#sort(unique(data1$di1f))
hero_any <- as.factor(mapvalues(data1$di1f, from=c(1,2),
                                to=c("Si",
                                     "No")))

#Heroína edad
#sort(unique(data1$di4f))
ages_hero <- cut(data1$di4f, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                 labels=c("No ha usado",
                          "1-10",
                          "11-20",
                          "21-30",
                          "31-40",
                          "41-50",
                          "51-60",
                          "Más de 61"))

#extasis
#sort(unique(data1$di1h))
ext_any <- as.factor(mapvalues(data1$di1h, from=c(1,2,9),
                               to=c("Si",
                                    "No",
                                    "No responde/No sabe")))

#extasis edad
#sort(unique(data1$di4h))
ages_ext <- cut(data1$di4h, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                labels=c("No ha usado",
                         "1-10",
                         "11-20",
                         "21-30",
                         "31-40",
                         "41-50",
                         "51-60",
                         "Más de 61"))

#Alcohol
#sort(unique(data1$al1))
alc_any <- as.factor(mapvalues(data1$al1, from=c(1,2),
                               to=c("Si",
                                    "No")))

#alcohol edad
#sort(unique(data1$al3))
ages_alc <- cut(data1$al3, breaks=c(-Inf,0,10,20,30,40,50,60,Inf), 
                labels=c("No ha usado",
                         "1-10",
                         "11-20",
                         "21-30",
                         "31-40",
                         "41-50",
                         "51-60",
                         "Más de 61"))

#sort(unique(data1$di3caa))
#uso 1 de 
uso_1 <- as.factor(mapvalues(data1$di3caa, from=c(1,2,3,4,5,6,7,9,-1), 
                                 to=c("Inyectada", 
                                      "Inhalada",
                                      "Aspirada",
                                      "Fumada",
                                      "Tragada",
                                      "Untada",
                                      "No como droga",
                                      "Prefiere no decir", 
                                      "Otra")))


#Cuantas veces
cuantas_veces <- as.factor(mapvalues(data1$di5c, from=c(1,2,3,4,5,-1), 
                             to=c("1-2 veces", 
                                  "3-5 veces",
                                  "6-10 veces",
                                  "11-49 veces",
                                  "50 o más",
                                  "Prefiere no decir")))

#ultimos 30 días
last_30 <- as.factor(mapvalues(data1$di8c, from=c(1,2,3,4,-1), 
                                     to=c("Sí, de 1 a 5 días", 
                                          "Sí, de 6 a 19 días",
                                          "Sí, de 20 a 30 días",
                                          "No",
                                          "Prefiere no decir")))

#ultimos 12 meses
last_12 <- as.factor(mapvalues(data1$di6c, from=c(1,2,-1), 
                               to=c("Sí",
                                    "No",
                                    "Prefiere no decir")))

#Alguna vez el cosumo afecto sus responsabilidades?
prob_1 <- as.factor(mapvalues(data1$ddg1a, from=c(1,2,-1),
                              to=c("Si",
                                   "No",
                                   "No responde")))

#provocó discusión?
prob_2 <- as.factor(mapvalues(data1$ddg2a, from=c(1,2,-1),
                              to=c("Si",
                                   "No",
                                   "No responde")))

#lo hace apesar de
prob_3 <- as.factor(mapvalues(data1$ddg2a1, from=c(1,2,-1),
                              to=c("Si",
                                   "No",
                                   "No responde")))

#uso en situación de peligro
prob_4 <- as.factor(mapvalues(data1$ddg3a, from=c(1,2,-1),
                              to=c("Si",
                                   "No",
                                   "No responde")))

#arrestado
prob_5 <- as.factor(mapvalues(data1$ddg4a, from=c(1,2,-1),
                              to=c("Si",
                                   "No",
                                   "No responde")))

#no se pudo resistir a usar
prob_6 <- as.factor(mapvalues(data1$ddg5a, from=c(1,2,-1),
                              to=c("Si",
                                   "No",
                                   "No responde")))

#aumentar dosis
prob_7 <- as.factor(mapvalues(data1$ddg6a, from=c(1,2,-1),
                              to=c("Si",
                                   "No",
                                   "No responde")))

#sintomas de abstinencia
prob_8 <- as.factor(mapvalues(data1$ddg7a, from=c(1,2,-1),
                              to=c("Si",
                                   "No",
                                   "No responde")))

#uso para evitar
prob_9 <- as.factor(mapvalues(data1$ddg8a, from=c(1,2,-1),
                              to=c("Si",
                                   "No",
                                   "No responde")))

#la uso a pesar de que prometió no hacerlo
prob_10 <- as.factor(mapvalues(data1$ddg9a, from=c(1,2,-1),
                               to=c("Si",
                                    "No",
                                    "No responde")))

# uso más de lo que se propuso
prob_11 <- as.factor(mapvalues(data1$ddg10a, from=c(1,2,-1),
                               to=c("Si",
                                    "No",
                                    "No responde")))

# se dio cuenta de que no podía dejarlo
prob_12 <- as.factor(mapvalues(data1$ddg11a, from=c(1,2,-1),
                               to=c("Si",
                                    "No",
                                    "No responde")))

# Por consumir no tenía tiempo para nada mas
prob_13 <- as.factor(mapvalues(data1$ddg12a, from=c(1,2,-1),
                               to=c("Si",
                                    "No",
                                    "No responde")))

# redujo tiempo para sus actividades por usar sustancia
prob_14 <- as.factor(mapvalues(data1$ddg13a, from=c(1,2,-1),
                               to=c("Si",
                                    "No",
                                    "No responde")))

#a pesar de que tenía un problema de salud
prob_15 <- as.factor(mapvalues(data1$ddg14a, from=c(1,2,-1),
                               to=c("Si",
                                    "No",
                                    "No responde")))

# 3 o mas de las anteriormente mencionadas
prob_16 <- as.factor(mapvalues(data1$ddg15a, from=c(1,2,-1),
                               to=c("Si",
                                    "No",
                                    "No responde")))

#### TRANSICION
data_matrix <- data1[,c("di1a", "di1b", "di1c", "di1d", "di1e", "di1f",
                       "di1g", "di1h", "dm1d", "dm1b")]

data_matrix <- data_matrix[data_matrix$di1a!=9,]
data_matrix <- data_matrix[data_matrix$di1b!=9,]
data_matrix <- data_matrix[data_matrix$di1c!=9,]
data_matrix <- data_matrix[data_matrix$di1d!=9,]
data_matrix <- data_matrix[data_matrix$di1e!=9,]
data_matrix <- data_matrix[data_matrix$di1f!=9,]
data_matrix <- data_matrix[data_matrix$di1g!=9,]
data_matrix <- data_matrix[data_matrix$di1h!=9,]
data_matrix <- data_matrix[data_matrix$dm1d!=9,]
data_matrix <- data_matrix[data_matrix$dm1b!=9,]

data_matrix$di1a[data_matrix$di1a==2] <- 0
data_matrix$di1b[data_matrix$di1b==2] <- 0
data_matrix$di1c[data_matrix$di1c==2] <- 0
data_matrix$di1d[data_matrix$di1d==2] <- 0
data_matrix$di1e[data_matrix$di1e==2] <- 0
data_matrix$di1f[data_matrix$di1f==2] <- 0
data_matrix$di1g[data_matrix$di1g==2] <- 0
data_matrix$di1h[data_matrix$di1h==2] <- 0
data_matrix$dm1d[data_matrix$dm1d==2] <- 0
data_matrix$dm1b[data_matrix$dm1b==2] <- 0

set.seed(1)
names(data_matrix) <- c("Marihuana", "Cocaína", "Crack", "Alucinógeno", "Inhalante",
                        "Heroína", "Estimulantes", "Ketamina", "Opio", "Tranquilizante")
mat <- as.matrix(data_matrix)
adyacency <- t(mat) %*% mat

```

# Análisis de personas que afirman haber usado 'crack'

```{r, echo=FALSE}
#Estados donde se consume
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=data1$desc_ent), fill = "#619DFF",
           stat="count", position="dodge") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 90)) +
  labs(x = "Estado",
       y="Cantidad") +
  ggtitle("Estados en los que se consume 'crack'")
```

```{r, echo=FALSE}
#Personas encuestadas por edades
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Rango de edades (años)") +
  ggtitle("Personas encuestadas por rango de edad")
```

```{r, echo=FALSE}
#Personas encuestadas por edades
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=indi),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=indi),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="¿Se considera indígena?") +
  ggtitle("Personas encuestadas que se consideran indígenas")
```

```{r, echo=FALSE}
#Personas encuestadas por estado civíl
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=status),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=status),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Estado civíl") +
  ggtitle("Personas encuestadas por estado civíl")
```

```{r, echo=FALSE}
#Personas encuestadas por religión
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=religion),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=religion),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Religión") +
  ggtitle("Personas encuestadas por religión")
```

```{r, echo=FALSE}
#Personas encuestadas por estado actual de estudios
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=actual_study),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=actual_study),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="¿Estudia actualmente?") +
  ggtitle("Personas encuestadas por estado actual de estudios")
```

```{r, echo=FALSE}
#Personas encuestadas por último grado de estudios
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=last_study),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=last_study),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Último grado de estudios alcanzado") +
  ggtitle("Personas encuestadas por último grado de estudios")
```

```{r, echo=FALSE}
#Personas encuestadas que trabajaron en los últimos 30 días
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=did_work),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=did_work),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Trabajó en los últimos 30 días") +
  ggtitle("Personas encuestadas que trabajaron en los últimos 30 días")
```

```{r, echo=FALSE}
#Principal motivo por el que no trabaja
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=why_work),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=why_work),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_color_gradientn(colours = rainbow(5)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Motivo") +
  ggtitle("Principal motivo por el que no trabaja")
```

```{r, echo=FALSE}
#Ocupación del encuestado
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=work),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=work),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_color_gradientn(colours = rainbow(5)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Ocupación") +
  ggtitle("Ocupación del encuestado")
```

```{r, echo=FALSE}
#El encuestado tiene o ha tenido hijos
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=sons),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=sons),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="¿Tiene o ha tenido hijos?") +
  ggtitle("¿El encuestado tiene o ha tenido hijos?")
```

```{r, echo=FALSE}
#Cuantos hijos viven con usted
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=much_sons),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=much_sons),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="¿Con cuantos hijos vive?") +
  ggtitle("¿Cuantos hijos viven con el encuestado?")
```

```{r, echo=FALSE}
#Alguno de sus hijos tiene problemas con alcohól o drogas
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=sons_drugs),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=sons_drugs),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("Alguno de sus hijos tiene problemas con alcohól o drogas")
```

```{r, echo=FALSE}
#Alguna vez ha usado tabaco
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=tabaco_any),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=tabaco_any),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿El encuestado fuma?")
```

```{r, echo=FALSE}
#Cuando comenzó
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages_tabaco),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages_tabaco),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Que edad tenía cuando comienza a fumar?")
```

```{r, echo=FALSE}
#Alguna vez ha usado tranquilizantes
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=tranq_any),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=tranq_any),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿El encuestado ha usado tranquilizantes?")
```

```{r, echo=FALSE}
#Cuando comenzó
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages_tranq),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages_tranq),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Que edad tenía cuando comienza a usar tranquilizantes?")
```

```{r, echo=FALSE}
#Alguna vez ha usado anfetamínicos
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=anf_any),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=anf_any),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿El encuestado ha usado anfetamínicos sin prescripción médica?")
```

```{r, echo=FALSE}
#Cuando comenzó
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages_anf),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages_anf),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Que edad tenía cuando comienza a usar anfetamínicos sin prescripción médica?")
```

```{r, echo=FALSE}
#Alguna vez ha usado marihuana
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=mar_any),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=mar_any),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿El encuestado ha usado marihuana?")
```

```{r, echo=FALSE}
#Cuando comenzó
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages_mar),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages_mar),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Que edad tenía cuando comienza a usar marihuana?")
```

```{r, echo=FALSE}
#Alguna vez ha usado cocaína
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=coc_any),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=coc_any),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿El encuestado ha usado cocaína?")
```

```{r, echo=FALSE}
#Cuando comenzó
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages_coc),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages_coc),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Que edad tenía cuando comienza a usar cocaína?")
```

```{r, echo=FALSE}
#Alguna vez ha usado alu
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=alu_any),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=alu_any),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿El encuestado ha usado alucinógenos?")
```

```{r, echo=FALSE}
#Cuando comenzó
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages_alu),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages_alu),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Que edad tenía cuando comienza a usar alucinógenos?")
```

```{r, echo=FALSE}
#Alguna vez ha usado inhalantes
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ina_any),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ina_any),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿El encuestado ha usado inhalantes?")
```

```{r, echo=FALSE}
#Cuando comenzó
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages_ina),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages_ina),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Que edad tenía cuando comienza a usar inhalantes?")
```

```{r, echo=FALSE}
#Alguna vez ha usado heroína
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=hero_any),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=hero_any),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿El encuestado ha usado heroína?")
```

```{r, echo=FALSE}
#Cuando comenzó
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages_hero),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages_hero),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Que edad tenía cuando comienza a usar heroína?")
```

```{r, echo=FALSE}
#Alguna vez ha usado éxtasis
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ext_any),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ext_any),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿El encuestado ha usado ketamina?")
```

```{r, echo=FALSE}
#Cuando comenzó
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages_ext),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages_ext),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Que edad tenía cuando comienza a usar ketamina?")
```

```{r, echo=FALSE}
#Alguna vez ha usado alcohol
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=alc_any),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=alc_any),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿El encuestado ha tomado bebidas alcohólicas?")
```

```{r, echo=FALSE}
#Cuando comenzó alcohol
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages_alc),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages_alc),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Que edad tenía cuando comienza a tomar bebídas alcohólicas?")
```

```{r, echo=FALSE}
#Cuando comenzó a usar la droga (principal)
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=ages_cra),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=ages_cra),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Que edad tenía cuando comienza a usar crack?")
```

```{r, echo=FALSE}
#Cuantas veces ha usado
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=cuantas_veces),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=cuantas_veces),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Cuantas veces ha usado 'crack'?")
```

```{r, echo=FALSE}
#Principal uso
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=uso_1),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=uso_1),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Principalmente como ha usado el 'crack'?")
```

```{r, echo=FALSE}
#La ha usado en los últimos 30 días
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=last_30),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=last_30),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Ha usado 'crack' en los últimos 30 días?")
```

```{r, echo=FALSE}
#La ha usado en los últimos 12 meses
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=last_12),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=last_12),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Ha usado 'crack' en los últimos 12 meses?")
```


```{r, echo=FALSE}
#Alguna vez el cosumo afecto sus responsabilidades?
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_1),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_1),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez el consumo de 'crack' dificultó sus actividades  
          como estudios, trabajo o en el hogar?")
```

```{r, echo=FALSE}
#provocó discusión?
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_2),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_2),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez el consumo de 'crack' le provocó discusiones  
          con familia, amigos, vecinos o compañeros?")
```

```{r, echo=FALSE}
#lo hace apesar de
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_3),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_3),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Siguió consumiendo 'crack' a pesar de dichos problemas?")
```

```{r, echo=FALSE}
#uso en situación de peligro
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_4),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_4),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Ha utilizado 'crack' manejando, en bicicleta
          o en alguna situación parecida?")
```

```{r, echo=FALSE}
#arrestado
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_5),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_5),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez ha sido arrestado por su comportamiento
          bajo los efectos del 'crack'?")
```

```{r, echo=FALSE}
#no se pudo resistir a usar
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_6),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_6),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez ha tenido tantas ganas de consumir 'crack'
          que no se pudo resistir?")
```

```{r, echo=FALSE}
#aumentar dosis
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_7),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_7),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez tuvo que aumentar su dosis para conseguir un efecto
          el cual ya no consiguió con la misma dósis de antes?")
```


```{r, echo=FALSE}
#sintomas de abstinencia
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_8),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_8),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez ha sentido malestares como cansancio, temblores o dolores 
            por no consumir 'crack'?")
```

```{r, echo=FALSE}
#uso para evitar
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_9),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_9),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez tuvo que usar 'crack' para aliviar dichos sintomas?")
```

```{r, echo=FALSE}
#la uso a pesar de que prometió no hacerlo
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_10),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_10),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez consumió 'crack' a pesar de 
          que prometió que ya no lo haría?")
```

```{r, echo=FALSE}
# uso más de lo que se propuso
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_11),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_11),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez consumió 'crack' más frecuentemente de 
          lo que se había propuesto?")
```

```{r, echo=FALSE}
# se dio cuenta de que no podía dejarlo
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_12),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_12),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez intentó dejar de consumir 'crack' y
          se dió cuenta de que no podía hacerlo?")
```

```{r, echo=FALSE}
# Por consumir no tenía tiempo para nada mas
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_13),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_13),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez pasó tanto tiempo consumiendo que se
          dio cuenta que ya no le quedaba tiempo para sus demás
          actividades?")
```

```{r, echo=FALSE}
# redujo tiempo para sus actividades por usar sustancia
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_14),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_14),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Ha tenido temporadas en que el uso de 'crack' hizo
          que disminuyera el tiempo que dedicaba a sus actividades?")
```

```{r, echo=FALSE}
#a pesar de que tenía un problema de salud
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_15),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_15),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Ha usado 'crack' a pesar de tener algun problema de 
          salud grave?")
```

```{r, echo=FALSE}
# 3 o mas de las anteriormente mencionadas
ggplot(as.data.frame(sex)) +
  theme_bw()+
  geom_bar(aes(x=sex, fill=prob_16),
           stat="count", position="dodge") +
  geom_text(aes(x=sex, label=..count.., group=prob_16),
            stat='count',
            position = position_dodge(width = 1),
            vjust = -0.5, size = 4) +
  scale_fill_brewer(palette = "Set3")  +
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Sexo",
       y="Cantidad",
       fill="Respuesta") +
  ggtitle("¿Alguna vez tuvo 3 o más de las situaciones anteriormente
          mencionadas?")
```

```{r, echo=FALSE}
#Diagrama de transición
g<-graph.adjacency(adyacency, mode="undirected", weighted=TRUE, diag=FALSE)
plot.igraph(g, layout=layout_in_circle, edge.arrow.size=0.1,
            edge.width=(E(g)$weight/max(E(g))),
            edge.label=E(g)$weight,
            edge.color="black",
            edge.curved=.3,
            vertex.label.color="blue",
            edge.label.color="red",
            vertex.size=40,
            vertex.color="yellow",
            main="Grafo de transición entre uso de drogas ilegales \n en personas que afirman haber usado 'crack'")
```









